pythonkey="python3"
anaxremotekey="scale.anaxremote"
flagmodule ="-m"
flaglocalloglevel="-l"
flagremoteloglevel="-r"
flagconfigfile="-f"
flagcount="-c"
flagmasterparallelism="-m"
flagslaveparallelism="-s"

containerskey = "containers"

jobskey="jobs"
jobkey="job"
jobdefkey="jobdef"

configurationkey="configuration"
confdirkey="configdirectory"
conffilekey="configfile"

logdirkey="logdir"
logfilekey="logfile"
phaseskey="phases"
operationkey="operation"
behaviorkey="behavior"


cleankey="clean"
anaxharnesloglevel="anaxharnesloglevel"
anaxremoteloglevel="anaxremoteloglevel"
prunekey="prune"

setupkey="setup"
countkey="count"
listkey="list"
queryrunningkey="queryrunning"
validaterunningkey="validaterunning"

executionkey="execution"
masterparallelismkey="masterparallelism"
slaveparallelismkey="slaveparallelism"
registerkey="register"
agreementskey="agreements"

teardownkey="teardown"
unregisterkey="unregister"

collectionkey="collection"
envvarkey="envvar"
pwkey="EXCHANGE_PW"
anonymizekey="anonymize"
archivekey="archive"
tarkey="tar"
compressionkey="compression"
gunzipkey="gunzip"
packagekey="package"
prefixkey="prefix"
destinationkey="destination"
storekey="store"

startkey="start"
stopkey="stop"
