#!/usr/bin/env bash
echo "STARTING SEND"
cd /home/parallels/PycharmProjects/edgescaler
python3 -m tools.hosts -l 0 -m 0 --headpseudodelay .05 scpsend -s /home/parallels/PycharmProjects/edgescaler/tools -d /root/scaler/ -f config.json 
echo "COMPLETED SEND"
