#!/usr/bin/env bash
echo "STARTING SEND"
cd /home/parallels/PycharmProjects/edgescaler
python3 -m tools.hosts -l 0 -m 0 scpsend -s /home/parallels/PycharmProjects/edgescaler/env -d /root/scaler/ -f config.json
echo "COMPLETED SEND"
