#!/usr/bin/env bash
echo "STARTING SEND"
cd /home/parallels/PycharmProjects/edgescaler
rm ~/Desktop/temp/scaler/*; 
cp *.sh ~/Desktop/temp/scaler/; 
python3 -m tools.hosts -l 0 -m 1 --headpseudodelay .05 scpsend -s /home/parallels/Desktop/temp/scaler/ -d /root/ -f config/config.json.allvalid &> send-scripts.log &
python3 -m tools.hosts -l 0 -m 1 --headpseudodelay .05 scpsend -s /home/parallels/PycharmProjects/edgescaler/scale -d /root/scaler/ -f config/config.json.allvalid &> send-scale.logs &
python3 -m tools.hosts -l 0 -m 1 --headpseudodelay .05 scpsend -s /home/parallels/PycharmProjects/edgescaler/tools -d /root/scaler/ -f config/config.json.allvalid &> send-tools.log &
python3 -m tools.hosts -l 0 -m 1 --headpseudodelay .05 scpsend -s /home/parallels/PycharmProjects/edgescaler/config -d /root/scaler/ -f config/config.json.allvalid &> send-config.log &
wait
echo "COMPLETED SEND"
